@SET FF_BUILD_NAME=x64
@SET BUILDTYPE=/clean
@SET SOLUTIONFILE1=ffdshow_2008.sln
@SET SOLUTIONFILE2=ffdshow_2008.sln
@SET BUILDTARGET1="Release|Win32"
@SET BUILDTARGET2="Release|Win32"

@build_script.bat