### FILES and DIRECTORIES ###

SRCS_C=\
    DllEntry.c \
    libavcodec/8bps.c \
    libavcodec/aac_ac3_parser.c \
    libavcodec/aacadtsdec.c \
    libavcodec/aacdec.c \
    libavcodec/aacps.c \
    libavcodec/aacsbr.c \
    libavcodec/aactab.c \
    libavcodec/aandcttab.c \
    libavcodec/aasc.c \
    libavcodec/ac3.c \
    libavcodec/ac3_parser.c \
    libavcodec/ac3dec.c \
    libavcodec/ac3dec_data.c \
    libavcodec/ac3dsp.c \
    libavcodec/ac3enc.c \
    libavcodec/ac3enc_fixed.c \
    libavcodec/ac3tab.c \
    libavcodec/adpcm.c \
    libavcodec/allcodecs.c \
    libavcodec/asv1.c \
    libavcodec/atrac.c \
    libavcodec/atrac3.c \
    libavcodec/audioconvert.c \
    libavcodec/avfft.c \
    libavcodec/avpacket.c \
    libavcodec/avs.c \
    libavcodec/bitstream.c \
    libavcodec/cabac.c \
    libavcodec/cavs.c \
    libavcodec/cavsdec.c \
    libavcodec/cavsdsp.c \
    libavcodec/celp_filters.c \
    libavcodec/celp_math.c \
    libavcodec/cinepak.c \
    libavcodec/cook.c \
    libavcodec/cscd.c \
    libavcodec/cyuv.c \
    libavcodec/dca.c \
    libavcodec/dcadsp.c \
    libavcodec/dca_parser.c \
    libavcodec/dct.c \
    libavcodec/dsputil.c \
    libavcodec/dv.c \
    libavcodec/eac3dec.c \
    libavcodec/eac3dec_data.c \
    libavcodec/error_resilience.c \
    libavcodec/faandct.c \
    libavcodec/faanidct.c \
    libavcodec/ffmpegContext.c \
    libavcodec/fft.c \
    libavcodec/ffv1.c \
    libavcodec/flac.c \
    libavcodec/flacdata.c \
    libavcodec/flacdec.c \
    libavcodec/flvdec.c \
    libavcodec/fmtconvert.c \
    libavcodec/fraps.c \
    libavcodec/g726.c \
    libavcodec/golomb.c \
    libavcodec/gsmdec.c \
    libavcodec/gsmdec_data.c \
    libavcodec/h261.c \
    libavcodec/h261dec.c \
    libavcodec/h263.c \
    libavcodec/h263_parser.c \
    libavcodec/h263dec.c \
    libavcodec/h264.c \
    libavcodec/h264_cabac.c \
    libavcodec/h264_cavlc.c \
    libavcodec/h264_direct.c \
    libavcodec/h264_loopfilter.c \
    libavcodec/h264_parser.c \
    libavcodec/h264_ps.c \
    libavcodec/h264_refs.c \
    libavcodec/h264_sei.c \
    libavcodec/h264dsp.c \
    libavcodec/h264idct.c \
    libavcodec/h264pred.c \
    libavcodec/huffman.c \
    libavcodec/huffyuv.c \
    libavcodec/imc.c \
    libavcodec/imgconvert.c \
    libavcodec/indeo2.c \
    libavcodec/indeo3.c \
    libavcodec/indeo5.c \
    libavcodec/intelh263dec.c \
    libavcodec/intrax8.c \
    libavcodec/intrax8dsp.c \
    libavcodec/ituh263dec.c \
    libavcodec/ivi_common.c \
    libavcodec/ivi_dsp.c \
    libavcodec/jfdctfst.c \
    libavcodec/jfdctint.c \
    libavcodec/jpegls.c \
    libavcodec/jpeglsdec.c \
    libavcodec/jrevdct.c \
    libavcodec/lcldec.c \
    libavcodec/libamr.c \
    libavcodec/ljpegenc.c \
    libavcodec/loco.c \
    libavcodec/mace.c \
    libavcodec/mdct.c \
    libavcodec/mjpeg.c \
    libavcodec/mjpeg_parser.c \
    libavcodec/mjpegdec.c \
    libavcodec/mjpegenc.c \
    libavcodec/mlp.c \
    libavcodec/mlp_parser.c \
    libavcodec/mlpdec.c \
    libavcodec/mlpdsp.c \
    libavcodec/motion_est.c \
    libavcodec/mpeg12.c \
    libavcodec/mpeg12data.c \
    libavcodec/mpeg4audio.c \
    libavcodec/mpeg4video.c \
    libavcodec/mpeg4video_parser.c \
    libavcodec/mpeg4videodec.c \
    libavcodec/mpegaudio.c \
    libavcodec/mpegaudiodata.c \
    libavcodec/mpegaudiodec.c \
    libavcodec/mpegaudiodec_float.c \
    libavcodec/mpegaudiodecheader.c \
    libavcodec/mpegaudio_parser.c \
    libavcodec/mpegvideo.c \
    libavcodec/mpegvideo_enc.c \
    libavcodec/msgsmdec.c \
    libavcodec/msmpeg4.c \
    libavcodec/msmpeg4data.c \
    libavcodec/msrle.c \
    libavcodec/msrledec.c \
    libavcodec/msvideo1.c \
    libavcodec/nellymoser.c \
    libavcodec/nellymoserdec.c \
    libavcodec/options.c \
    libavcodec/parser.c \
    libavcodec/pcm.c \
    libavcodec/png.c \
    libavcodec/pngdec.c \
    libavcodec/pngenc.c \
    libavcodec/qdm2.c \
    libavcodec/qpeg.c \
    libavcodec/qtrle.c \
    libavcodec/ra144.c \
    libavcodec/ra144dec.c \
    libavcodec/ra288.c \
    libavcodec/rangecoder.c \
    libavcodec/ratecontrol.c \
    libavcodec/rdft.c \
    libavcodec/rpza.c \
    libavcodec/rtjpeg.c \
    libavcodec/rv10.c \
    libavcodec/rv30.c \
    libavcodec/rv30dsp.c \
    libavcodec/rv34.c \
    libavcodec/rv40.c \
    libavcodec/rv40dsp.c \
    libavcodec/simple_idct.c \
    libavcodec/sp5xdec.c \
    libavcodec/svq1.c \
    libavcodec/svq1dec.c \
    libavcodec/svq3.c \
    libavcodec/synth_filter.c \
    libavcodec/truemotion1.c \
    libavcodec/truemotion2.c \
    libavcodec/truespeech.c \
    libavcodec/tscc.c \
    libavcodec/tta.c \
    libavcodec/ulti.c \
    libavcodec/utils.c \
    libavcodec/vc1.c \
    libavcodec/vc1data.c \
    libavcodec/vc1dec.c \
    libavcodec/vc1dsp.c \
    libavcodec/vcr1.c \
    libavcodec/vorbis.c \
    libavcodec/vorbis_data.c \
    libavcodec/vorbis_dec.c \
    libavcodec/vp3.c \
    libavcodec/vp3dsp.c \
    libavcodec/vp5.c \
    libavcodec/vp56.c \
    libavcodec/vp56data.c \
    libavcodec/vp56dsp.c \
    libavcodec/vp56rac.c \
    libavcodec/vp6.c \
    libavcodec/vp6dsp.c \
    libavcodec/vp8.c \
    libavcodec/vp8dsp.c \
    libavcodec/w32thread.c \
    libavcodec/wavpack.c \
    libavcodec/wma.c \
    libavcodec/wmadec.c \
    libavcodec/wmv2.c \
    libavcodec/wmv2dec.c \
    libavcodec/wnv1.c \
    libavcodec/xiph.c \
    libavcodec/xl.c \
    libavcodec/zmbv.c \
    libavcodec/amr_float/interf_dec.c \
    libavcodec/amr_float/sp_dec.c \
    \
    libavcodec/x86/ac3dsp_mmx.c \
    libavcodec/x86/cavsdsp_mmx.c \
    libavcodec/x86/dct32_sse.c \
    libavcodec/x86/dsputil_mmx.c \
    libavcodec/x86/dsputilenc_mmx.c \
    libavcodec/x86/fdct_mmx.c \
    libavcodec/x86/fft.c \
    libavcodec/x86/fft_3dn.c \
    libavcodec/x86/fft_3dn2.c \
    libavcodec/x86/fft_sse.c \
    libavcodec/x86/fmtconvert_mmx.c \
    libavcodec/x86/h264_intrapred_init.c \
    libavcodec/x86/h264dsp_mmx.c \
    libavcodec/x86/idct_mmx.c \
    libavcodec/x86/idct_mmx_xvid.c \
    libavcodec/x86/idct_sse2_xvid.c \
    libavcodec/x86/mlpdsp.c \
    libavcodec/x86/motion_est_mmx.c \
    libavcodec/x86/mpegaudiodec_mmx.c \
    libavcodec/x86/mpegvideo_mmx.c \
    libavcodec/x86/simple_idct_mmx.c \
    libavcodec/x86/vc1dsp_mmx.c \
    libavcodec/x86/vp56dsp_init.c \
    libavcodec/x86/vp8dsp-init.c \
    \
    libavutil/audioconvert.c \
    libavutil/avstring.c \
    libavutil/cpu.c \
    libavutil/crc.c \
    libavutil/eval.c \
    libavutil/imgutils.c \
    libavutil/intfloat_readwrite.c \
    libavutil/inverse.c \
    libavutil/lfg.c \
    libavutil/lls.c \
    libavutil/log.c \
    libavutil/lzo.c \
    libavutil/mathematics.c \
    libavutil/md5.c \
    libavutil/mem.c \
    libavutil/pixdesc.c \
    libavutil/random_seed.c \
    libavutil/rational.c \
    libavutil/samplefmt.c \
    \
    libavutil/x86/cpu.c \
    \
    libavfilter/asrc_anullsrc.c \
    libavfilter/avfilter.c \
    libavfilter/avfiltergraph.c \
    libavfilter/defaults.c \
    libavfilter/formats.c \
    libavfilter/vf_gradfun.c \
    libavfilter/vf_yadif.c \
    libavfilter/yadif_thread.c \
    \
    libavfilter/x86/gradfun.c \
    libavfilter/x86/yadif.c \
    \
    libswscale/rgb2rgb.c \
    libswscale/swscale.c \
    libswscale/swutils.c \
    libswscale/yuv2rgb.c \
    libswscale/sww32thread.c \
    libswscale/x86/yuv2rgb_mmx.c \
    \
    libpostproc/postprocess.c \
    \
    ../zlib/adler32.c \
    ../zlib/compress.c \
    ../zlib/crc32.c \
    ../zlib/deflate.c \
    ../zlib/gzclose.c \
    ../zlib/gzlib.c \
    ../zlib/gzread.c \
    ../zlib/gzwrite.c \
    ../zlib/infback.c \
    ../zlib/inffast.c \
    ../zlib/inflate.c \
    ../zlib/inftrees.c \
    ../zlib/trees.c \
    ../zlib/uncompr.c \
    ../zlib/zutil.c

SRCS_YASM=\
    libavcodec/x86/ac3dsp.asm \
    libavcodec/x86/dsputil_yasm.asm \
    libavcodec/x86/dsputilenc_yasm.asm \
    libavcodec/x86/fft_mmx.asm \
    libavcodec/x86/fmtconvert.asm \
    libavcodec/x86/h264_chromamc.asm \
    libavcodec/x86/h264_deblock.asm \
    libavcodec/x86/h264_idct.asm \
    libavcodec/x86/h264_intrapred.asm \
    libavcodec/x86/h264_weight.asm \
    libavcodec/x86/vc1dsp_yasm.asm \
    libavcodec/x86/vp3dsp.asm \
    libavcodec/x86/vp56dsp.asm \
    libavcodec/x86/vp8dsp.asm \
    libavcodec/x86/x86util.asm


ifeq ($(64BIT),yes)
    OBJ_DIR=../../obj/MinGW64/ffmpeg/
    ZLIB_OBJ_DIR=../../obj/MinGW64/zlib/
    TARGET_LIB_DIR=../../bin/
else
    OBJ_DIR=../../obj/MinGW32/ffmpeg/
    ZLIB_OBJ_DIR=../../obj/MinGW32/zlib/
    TARGET_LIB_DIR=../../bin/
endif

OBJ_DIRS=\
    $(OBJ_DIR) \
    $(OBJ_DIR)libavcodec \
    $(OBJ_DIR)libavcodec/amr_float \
    $(OBJ_DIR)libavcodec/x86 \
    $(OBJ_DIR)libavcore \
    $(OBJ_DIR)libavutil \
    $(OBJ_DIR)libavutil/x86 \
    $(OBJ_DIR)libavfilter \
    $(OBJ_DIR)libavfilter/x86 \
    $(OBJ_DIR)libswscale \
    $(OBJ_DIR)libswscale/x86 \
    $(OBJ_DIR)libpostproc \
    $(ZLIB_OBJ_DIR)

TARGET_LIB=$(TARGET_LIB_DIR)ffmpeg.dll

DEF=ffmpeg.def


### SETTINGS ###

CFLAGS=-I. -Ilibavcodec -Ilibavutil -Ilibavcore -I../imgFilters -I../zlib -DHAVE_AV_CONFIG_H -D_ISOC99_SOURCE -D_POSIX_C_SOURCE=200112 -std=gnu99

ifeq ($(64BIT),yes)
    CFLAGS+=-DARCH_X86_64
else
    CFLAGS+=-DARCH_X86_32
endif

#CFLAGS+=-save-temps
#CFLAGS+=-fverbose-asm

YASMFLAGS+=-Pconfig.asm


### INCLUDES ###

include ../makefile_c.inc


### TARGETS ###

.all: outdirs $(TARGET_LIB)

.PHONY: outdirs $(OBJ_DIRS)
outdirs: $(OBJ_DIRS)
$(OBJ_DIRS):
	$(shell test -d $(@) || mkdir -p $(@))


.PHONY: clean
clean:
	rm -f $(TARGET_LIB)
	rm -r -f $(OBJ_DIR)
	rm -r -f $(ZLIB_OBJ_DIR)
