//Empty declarations of MMX intrinisc to make ffdshow.ax 
//link successfully with Microsoft 64-bit C++ Compiler.
void _mm_setzero_si64() {}
void _mm_set_pi32() {}
void _mm_set_pi16() {}
void _mm_set_pi8() {}
void _mm_set1_pi32() {}
void _mm_set1_pi16() {}
void _mm_set1_pi8() {}

void _m_psubb() {}
void _m_paddusb() {}
void _m_psubsw() {}
void _m_psubsb() {}
void _m_paddw() {}
void _m_empty() {}
void _m_packuswb() {}
void _m_psrlwi() {}
void _m_pmullw() {}
void _m_from_int() {}
void _m_to_int() {}
void _m_psrlqi() {}
void _m_paddd() {}
void _m_pmaddwd() {}
void _m_punpcklbw() {}
void _m_paddb() {}
void _m_por() {}
void _m_pand() {}
void _m_pandn() {}
void _m_pcmpgtb() {}
void _m_psubusb() {}
void _m_psrawi() {}
void _m_psubw() {}
void _m_psllwi() {}
void _m_paddusw() {}
void _m_pxor() {}
void _m_pslldi() {}
void _m_punpckhbw() {}
void _m_punpcklwd() {}
void _m_punpckldq() {}
void _m_pcmpgtw() {}
void _m_pcmpgtd() {}
void _m_pcmpeqb() {}
void _m_pcmpeqd() {}
void _m_pmaxub() {}
void _m_pminub() {}
void _m_pavgb() {}
void _m_pshufw() {}
void _m_punpckhwd() {}
void _m_punpckhdq() {}
void _m_psrldi() {}
void _m_psubd() {}
void _m_pmulhw() {}
void _m_psllqi() {}
void _m_pcmpeqw() {}
void _m_pmulhuw() {}
void _m_psadbw() {}
void _m_paddsb() {}
void _m_packsswb() {}
void _m_psradi() {}
void _m_paddsw() {}
void _m_psubusw() {}
void _m_packssdw() {}
void _m_pminsw() {}
void _m_pmaxsw() {}
void _mm_stream_pi() {}
void _m_psraw() {}

void _mm_cvt_ps2pi() {}
void _mm_cvt_pi2ps() {}
void _mm_movepi64_pi64() {}
